### ISSUE TITLE
Argument Error happening *sometimes* in Docker running tests

### ISSUE THREAD

**Issue by GenericJam** [elixir-ecto/postgrex#493]
This is super strange. Not having this error while running locally or while running releases in Docker. This error happens _sometimes_ (1/4 or so runs) while running tests in docker. Two separate docker containers running Elixir and Postgres.

I thought it may be because Docker is caching so I pruned the docker images between runs and it still fails on the first run sometimes.

The migration runs but fails the first time the code tries to use the DB.

**Edit: Upon further inspection this is happening *every* time but sometimes it will recover and finish running the tests and sometimes it completely fails.

```
14:54:00.712 pid=<0.607.0> [error] GenServer #PID<0.607.0> terminating
** (ArgumentError) unknown registry: Postgrex.TypeManager
    (elixir) lib/registry.ex:1243: Registry.key_info!/1
    (elixir) lib/registry.ex:568: Registry.lookup/2
    (postgrex) lib/postgrex/type_supervisor.ex:29: Postgrex.TypeSupervisor.locate/2
    (postgrex) lib/postgrex/protocol.ex:772: Postgrex.Protocol.bootstrap/3
    (postgrex) lib/postgrex/protocol.ex:577: Postgrex.Protocol.handshake/2
    (db_connection) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (ArgumentError) argument error
    (stdlib) :ets.lookup_element(Ecto.Repo.Registry, #PID<0.626.0>, 3)
    (ecto) lib/ecto/repo/registry.ex:18: Ecto.Repo.Registry.lookup/1
    (ecto) lib/ecto/repo/queryable.ex:137: Ecto.Repo.Queryable.execute/4
    (gamgee_elixir) lib/gamgee_elixir/db/db_impl/db_impl.ex:43: GamgeeElixir.DBImpl.reset_db/0
    test/test_helper.exs:12: (file)
```
Dockerfile:
```
FROM elixir:1.9.4-alpine

ENV MIX_ENV=test
ENV DATABASE_HOST=**

WORKDIR /opt/app

RUN mix local.rebar --force && \
  mix local.hex --force

COPY . .

RUN mix do deps.get, deps.compile, compile
```

docker-compose.xml:

```
version: "3.5"

services:
  elixir_test:
    build:
      context: ../
      dockerfile: ./test/Dockerfile
    volumes:
      - "./log:/opt/app/log"
    depends_on:
      - postgresql
    command: mix test

  postgresql:
    image: postgres:10-alpine
    environment:
      POSTGRES_DB: **
      POSTGRES_USER: **
      POSTGRES_PASSWORD: **
```
