### ISSUE TITLE
Incompatibilities with Yugabyte  (Odyssey connection pooler)

### ISSUE THREAD

**Issue by munjalpatel** [elixir-ecto/postgrex#733]
### Elixir version

Elixir 1.18.1 (compiled with Erlang/OTP 27)

### Database and Version

Yugabyte 2.25

### Postgrex Version

0.20.0

### Current behavior

The following fails

```elixir
iex> {:ok, pid} = Postgrex.start_link(hostname: "localhost", port: 5433, username: "myapp", password: "myapp", database: "myapp")
{:ok, #PID<0.394.0>}

iex> Postgrex.query(pid, "select * from pg_catalog.pg_database", [])
[error] Postgrex.Protocol (#PID<0.396.0>) disconnected: ** (DBConnection.ConnectionError) tcp recv (idle): closed
{:error,
 %DBConnection.ConnectionError{
   message: "tcp recv (idle): closed",
   severity: :error,
   reason: :error
 }}
```

However, when I execute the same query with any standard Postgrex client (Beekeper Studio), it works fine.

**docker-compose**
```yaml
services:
  db:
    image: yugabytedb/yugabyte:2.25.0.0-b489@sha256:6eecf79469e2a55c95d76d16256bf4d124efa86f9f2cf73a008dcb557298c885
    container_name: db
    restart: always
    command: [
      "bin/yugabyted",
      "start",
      "--listen=db",
      "--background=false",
      "--tserver_flags=flagfile=/ydb.conf",
      "--base_dir=/home/yugabyte/yb_data",
      "--callhome=false"
    ]
    ports:
      - "5433:5433"
      - "7003:7000"
      - "15433:15433"
    volumes:
      - ./ydb.conf:/ydb.conf
      - ./data:/home/yugabyte/yb_data
    networks:
      - db
    healthcheck:
      test: ["CMD-SHELL", "postgres/bin/pg_isready -U yugabyte -h db"]
      interval: 1s
      timeout: 60s
      retries: 65
      start_period: 1s

  db-setup:
      image: yugabytedb/yugabyte:2.25.0.0-b489@sha256:6eecf79469e2a55c95d76d16256bf4d124efa86f9f2cf73a008dcb557298c885
      container_name: db-setup
      command: ["bin/ysqlsh", "-h", "db", "-U", "yugabyte", "-f", "/setup.sql"]
      environment:
        - PGPASSWORD=yugabyte
      volumes:
        - ./setup.sql:/setup.sql
      networks:
        - db
      depends_on:
        db:
          condition: service_healthy

networks:
  db:
    driver: bridge
```

**ydb.conf**
```conf
--enable_ysql_conn_mgr=true
--allowed_preview_flags_csv=enable_ysql_conn_mgr
--ysql_conn_mgr_log_settings=log_debug,log_config,log_session,log_query,log_stats
```

**setup.sql**
```sql
CREATE ROLE myapp WITH LOGIN PASSWORD 'myapp' NOSUPERUSER CREATEDB CREATEROLE;

CREATE DATABASE myapp;
ALTER DATABASE myapp OWNER TO myapp;

REVOKE CONNECT ON DATABASE myapp FROM PUBLIC;
GRANT CONNECT ON DATABASE myapp TO myapp;
```

### Expected behavior

I would expect `Postgrex.query(pid, "select * from pg_catalog.pg_database", [])` to return `{:ok, result}`
